version: '3'
services:
  #Postgres
  db:
    image: postgres
    container_name: db
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    restart: always
  #PG Admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${DB_USER}@admin.com'
      PGADMIN_DEFAULT_PASSWORD: '${DB_PASSWORD}'
    restart: always
  #Application
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    restart: always
